#!/bin/bash

rg_name=cotiss-website
vnet_name=cotiss-vnet
subnet_name=cotiss-subnet
public_ip_name=cotiss-IP
lb_name=cotiss-lb
front_end_name=cotiss-frontend
backend_Name=cotiss-backend
health_probe_name=cotiss-healthprobe
nsg_name=cotiss-nsg
nsg_rule_name=cotiss-nsg-rule

vm_name=base #vm to copy
image_gallery_name=mygallery
image_defintion=website-base-img
offer=debian-10
publisher=debian
sku=10

lb_name=cotiss-scalesetLB
lb_rule_name=load-balancer-rule
front_end_ip_name=cotiss-front-end-ip-lb-399110124
address_pool_name=cotiss-address-pool

scale_set_name=cotiss-scaleset

subscriptionID=$(az account show --query id --output tsv)
vmID=$(az vm get-instance-view -g $rg_name -n $vm_name --query id)




az network vnet create --resource-group $rg_name --location eastus --name $vnet_name --address-prefixes 10.1.0.0/16 --subnet-name $subnet_name --subnet-prefixes 10.1.0.0/24

az network public-ip create --resource-group $rg_name --name $public_ip_name --sku Standard --zone 1 2 3

az network lb create --resource-group $rg_name --name $lb_name --sku Standard --public-ip-address $public_ip_name --frontend-ip-name $front_end_name  --backend-pool-name $backend_Name

az network lb probe create --resource-group $rg_name --lb-name $lb_name --name $health_probe_name --protocol tcp --port 80

az network lb rule create --resource-group $rg_name --lb-name $lb_name --name myHTTPRule --protocol tcp --frontend-port 80 --backend-port 80 --frontend-ip-name $front_end_name --backend-pool-name $backend_Name --probe-name $health_probe_name --disable-outbound-snat true --idle-timeout 15 --enable-tcp-reset true


az network nsg rule create --resource-group $rg_name --nsg-name $nsg_name --name $nsg_rule_name --protocol '*' --direction inbound --source-address-prefix '*' --source-port-range '*'  --destination-address-prefix '*'  --destination-port-range 80 --access allow --priority 200
